#!/usr/bin/env php
<?php

namespace FizzFuzz;

use GuzzleHttp\Client as Client;
use GuzzleHttp\Exception\ClientException;
use Symfony\Component\Console\Application;
use Symfony\Component\Finder\Finder;
use FizzFuzz\Tasks;

include __DIR__.'/../../../autoload.php';

$finder = new Finder();
$client = new Client();

$application = new Application();
$application->add(new Tasks\RunTask($finder, $client));
$application->run();
